### PR TITLE
Add travis step to check whitespace

### PR DESCRIPTION
**Pull request by ccope**
- [X] Add the code checks, get red build
- [x]  Apply fixes, get green build
- [ ] Commit .git-blame-ignore-revs file after review

### CODE REVIEW

**Comment by ccope** [comment]
Example of a failing build: https://app.travis-ci.com/github/libfuse/sshfs/builds/236422045

**Comment by ccope** [comment]
This supersedes the whitespace fixes #257 but the editorconfig would still be useful.

**Comment by Nikratio** [comment]
Looks good, thank you!

**Comment by Nikratio** [comment]
Could you make the `.git-blame-ignore-revs` as well, now that this is merged?

**Pull request merged**
