### PR TITLE
Add build badge

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by Nikratio** [comment]
Could you explain in what situation this is useful?

**Comment by fulldecent** [comment]
This allows people to know that passing the build is important and that the project is high quality because it has automated builds set up.

**Comment by Nikratio** [comment]
Sorry, I do not see how having automated builds setup shows that the project is high quality. Rather, it looks like providing free advertising for Travis. While I appreciate the service they are providing, I do not think that the SSHFS readme is the right place to place advertisements for a commercial company.

**Comment by fulldecent** [comment]
Yes, that makes sense. And I also wish there was a more open and neutral way to set up builds.

**Pull request closed without merging**
